name: 'Auto Branch Sync'
description: 'Automatically synchronize directories to other branches within the same repository.'
author: Bjorn Lu
branding:
  icon: refresh-cw
  color: green
inputs:
  map:
    description: 'A line-separated list following "<source-dir> -> <target-branch>" format'
    required: true
  skip-unchanged-check:
    description: 'Skip the check for unchanged files'
    required: false
    default: false
  dry-run:
    description: 'Do not push changes to the target branch'
    required: false
    default: false
  token:
    description: 'Git authentication token (e.g. GH_TOKEN)'
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
