name: Test

on:
  workflow_dispatch:
    inputs:
      skip-unchanged-check:
        type: boolean
        default: false
      dry-run:
        type: boolean
        default: false
  push:
    branches:
      - master

env:
  ACTIONS_RUNNER_DEBUG: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: ./
        with:
          map: |
            / -> sync/root
            /test-fixtures -> sync/fixtures
          skip-unchanged-check: ${{ inputs.skip-unchanged-check }}
          dry-run: ${{ inputs.dry-run }}
