name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: ./
        with:
          map: |
            / -> sync/root
            /test-fixtures -> sync/fixtures
